name: ci-python-unittest
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REDIS_SECRET: "password-test-ci"
      BOX_REDIS_PASS: "${REDIS_SECRET}"
      BOX_REDIS_HOST: "redis"
    services:
      redis:
        image: redis:6.2-alpine
        env:
          REDIS_PASSWORD: ${{ env.REDIS_SECRET }}
          REDIS_SAVE: "20 1"
          REDIS_LOGLEVEL: "warning"
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s boxcraft/tests/ -p "test_*.py"
