name: ci-python-unittest
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REDIS_SECRET: "password-test-ci"
      BOX_REDIS_PASS: "password-test-ci"
      BOX_REDIS_HOST: "localhost"
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Start Redis service
      run: |
        echo "Starting Redis service..."
        docker run --rm -d --name redis -p 6379:6379 redis:6.2-alpine redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_SECRET}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    
    - name: Wait for Redis to be ready
      run: |
        echo "Waiting for Redis to be ready..."
        until python -c "import redis; conn = redis.Redis(host='localhost', port=6379, password='${REDIS_SECRET}'); conn.get('test_key')" > /dev/null 2>&1; do
            echo "Redis is not ready yet. Retrying in 5 seconds..."
            sleep 5
        done
        echo "Redis is ready!"
    
    - name: Run tests
      run: |
        #python -m unittest discover -s boxcraft/tests/ -p "test_*.py" # failed_resolved_domain_name
        python -m unittest boxcraft/tests/test_box.py -vvv